name: Publish

on:
  push:
    branches: [ master ]

permissions: write-all

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  publish:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0.x
    - name: Build Solution
      run: InferModuleSchema.sln
    - name: Publish
      run: dotnet run --project ./build/Build.fsproj publish